name: Deploy to Server

on:
  push:
    branches:
      - staging
      - production

jobs:
  deploy:
    if: contains(['staging','production'], github.ref_name)
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy via rsync
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            ./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/html/wp-content/themes/climateAction-wordpress"

      - name: Clear Autoptimize cache
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p ${{ secrets.SSH_PORT }} \
            -o StrictHostKeyChecking=no \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "cd ~/html && wp autoptimize clear"

